name: CI Pipeline with Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests with Coverage
        run: |
          pytest --cov=app --cov-report=xml

      - name: Install Cypress (for UI tests)
        run: |
          npm install cypress

      - name: Run Cypress UI Tests
        uses: cypress-io/github-action@v6
        with:
          build: npm install
          start: npm run start
          wait-on: 'http://localhost:3000'

      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
